### PR TITLE
feat: add languages and multi-directory options (don't merge)

### PR DESCRIPTION
**Pull request by OmarIthawi**
This includes a demo script, that will eventually be included into
atlas.

Run the script: `$ ./sparse-checkout-demo.sh`

Press Enter to see the demos in action.

Alternatively, I've recorded an asciinema demo: https://asciinema.org/a/JuFEu2qQEZOvI75RFeczewLcm

### Directory mapping design
The goal is to introduce a directory mapping feature inspired from Docker's mapping syntax `from_dir:to_dir` in which that directories from the `openedx-translations` repo is mapped to custom directories in the local repo:

For example, let's imagine atlas has the feature and the `--directory` option would include `translations/frontend-app-learning/src/i18n/messages:frontend-app-learning` 

This causes that files inside `openedx-translations` in the directory `translations/frontend-app-learning/src/i18n/messages` would be copied into `frontend-app-learning` in the local repo.

### Languages filter design
The language filter is a basic prefix to each directory to generate proper `git sparse-checkout` rules.

For each language/directory pair two rules are added:
```
# Include directories that matches the language pattern e.g. `/ar/`
git sparse-checkout add "${DIR_FROM}/**/${ATLAS_LANG}/**"
# Include files that matches the language pattern e.g. `ar.*`
git sparse-checkout add "${DIR_FROM}/**/${ATLAS_LANG}.*"
```

That's a lot of rules, but git handles them fine.

### Checkout learning MFE files

```
$ atlas pull --repo='Zeit-Labs/openedx-translations' --branch='learning-mfe-translations' --directory='translations/frontend-app-learning/src/i18n/messages:frontend-app-learning translations/frontend-component-footer/src/i18n/messages:frontend-component-footer translations/frontend-component-header/src/i18n/messages:frontend-component-header' --languages='fr_CA,ar,es_419'
```

#### Sparse checkout tree
```
.
└── translations
    ├── frontend-app-learning
    │   └── src
    │       └── i18n
    │           └── messages
    │               ├── ar.json
    │               ├── es_419.json
    │               └── fr_CA.json
    ├── frontend-component-footer
    │   └── src
    │       └── i18n
    │           └── messages
    │               ├── ar.json
    │               ├── es_419.json
    │               └── fr_CA.json
    └── frontend-component-header
        └── src
            └── i18n
                └── messages
                    ├── ar.json
                    ├── es_419.json
                    └── fr_CA.json
```

#### Final directory structure tree
````
.
├── frontend-app-learning
│   ├── ar.json
│   ├── es_419.json
│   └── fr_CA.json
├── frontend-component-footer
│   ├── ar.json
│   ├── es_419.json
│   └── fr_CA.json
└── frontend-component-header
    ├── ar.json
    ├── es_419.json
    └── fr_CA.json

3 directories, 9 files
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by brian-smith-tcril** [comment]
This looks really good! I'd like to see how you plan on integrating this into atlas. The tree preview is really cool and would be a great feature to add when using atlas interactively, but we also need to plan for non-interactive atlas use.

Looking forward to seeing the next version of this where everything is integrated!

**Comment by OmarIthawi** [comment]
> This looks really good! I'd like to see how you plan on integrating this into atlas. The tree preview is really cool and would be a great feature to add when using atlas interactively, but we also need to plan for non-interactive atlas use.

That's a good idea! I was mainly focusing on this demo, but I imagine a `--dry-run` option which would print the two tree instead of copying the files. That should be a good idea.

I might, be a bit more liberal on the way `--directory` parameter is being handled, apart from that I'll make incremental changes until atlas is completely migrated.

Thanks for the review, I'll close this PR and move into non-demo PRs.

**Comment by OmarIthawi** [comment]
> This looks really good! I'd like to see how you plan on integrating this into atlas. The tree preview is really cool and would be a great feature to add when using atlas interactively, but we also need to plan for non-interactive atlas use.

@brian-smith-tcril That's a good idea! I was mainly focusing on this demo, but I imagine a `--dry-run` option which would print the two tree instead of copying the files. That should be a good idea.

I might, be a bit more liberal on the way `--directory` parameter is being handled, apart from that I'll make incremental changes until atlas is completely migrated.

Thanks for the review, I'll close this PR and move into non-demo PRs.

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-atlas&entry.867055334=https://github.com/openedx/openedx-atlas/pull/10&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-04-05+14:15&entry.1917517419=2023-04-05+20:51&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
